#      middlewares: authelia@docker

http:
  # Add the router
  routers:
    lxd-router:
      rule: "Host(`www.warringtonconservatives.org`) || Host(`warringtonconservatives.org`)"
      entryPoints:
      - https
      tls:
        certResolver: letsencrypt
      service: lxd-service
      middlewares: testheader@docker
    bi5-router:
      rule: "Host(`video.flynnhome.org`)"
      entryPoints:
      - https
      tls:
        certResolver: letsencrypt
      service: bi5-service

  # Add the service
  services:
    lxd-service:
      loadBalancer:
        servers:
        - url: "http://192.168.50.181:81" 
        passHostHeader: true
    bi5-service:
      loadBalancer:
        servers:
        - url: "http://192.168.50.61:81" 
        passHostHeader: true
